### ISSUE TITLE
First Meeting Agenda: Planning Group Norms

### ISSUE THREAD

**Issue by hudaalamassi** [MIT-Emerging-Talent/ET6-foundations-group-15#1]
### First Meeting Agenda

**Day**: Monday  
**Time**: 2:00 PM (GMT+2)

---

### Agenda Points:

- [x] **Introductions and Getting to Know Each Other**
  - Brief self-introductions (name, background)
  
- [ ] #2
  - **Questions to Discuss**:  
    - What is our timeline for this project?  
    - What do we want to learn throughout this process?  
    - What problems are we aiming to solve (List of code challenges)?  
    - What strategy will we use to tackle these challenges? Should we incorporate recursion for example?  

- [ ] **Establishing Group Norms**
  - **Key Points for Discussion**:  
    - Guidelines for reviewing code (focus on the code, not the individual)  
    - Respecting each group member’s time and contributions  
    - Emphasizing clear, explicit communication  

- [ ] **Understanding ZPD (Zone of Proximal Development)**
  - What challenges should we tackle (difficult vs. easier challenges)?  
  - How can we focus on development processes and collaboration instead of just problem-solving?  

- [ ] **Supporting Each Other**
  - How can we best support each other in this project?  
  - **How to ask for help**: 
    - 0-30 minutes: Try to resolve independently  
    - 30-60 minutes: Reach out to the group  
    - 60+ minutes: Contact coaches via Slack or GitHub  

- [ ] **Communication in Conflict Situations**
  - **Handling decision-making conflicts**: What happens when a group can't decide on a course of action? ("Cannot-do-zone")  
  - When should we escalate an issue to a mentor for guidance?

- [x] **Revision for "Tools for Collaborative Development Assignment"**
  - Review **Git & GitHub** best practices and important concepts.

- [x] **Group Repository on GitHub**
  - Focus on reviewing and discussing the **`ISSUE_TEMPLATE`** and **`collaboration`** folders.

- [x] **Next Steps After the Meeting** (subject to change after discussion).
  - Review and study the **[Collaboration Guide](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-15/tree/main/collaboration/guide)**.   
  - Study **GitHub Code Review Tools**.  
  - Plan: Begin coding after completing the necessary preparations.

**Comment by byabdallah** [comment]
We will basically go through the folders through the files in the repo and set a deadline for filling what should be filled. Looking forward to meet you!

**Comment by hudaalamassi** [comment]
# Meeting Summary and Next Steps

## Strengthening Collaboration
- We reviewed the repository and the collaboration folder to ensure clarity and alignment.
- Moving forward, everyone will work collaboratively on a designated branch, maintaining teamwork and consistency.

## Commitment to Best Practices
- Each team member will:
  - Clone the branch, contribute, and stay updated by regularly pulling changes.
  - Ensure all work follows **Markdown rules** to maintain proper formatting and structure.

## Assignment Goals
- We aim to complete both assignments by **Thursday** and are focused on achieving this target.

## Continuing the Conversation
- Not all agenda points were addressed during this meeting, so we’ll plan another session soon to cover the remaining topics.

## Next Priority
- While we discussed the collaboration folder, the **ISSUE_TEMPLATE** folder still needs to be addressed in the upcoming meeting.

**Comment by hudaalamassi** [comment]
- Not all agenda points were addressed during this meeting, so we’ll plan another session soon to cover the remaining topics.
